version: "2.1"

services:
  redis:
    image: 'redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - /Users/chul/redis/data:/redis/data
      - DISABLE_COMMANDS=CONFIG
    restart: always

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: chulm/shorturl/app:latest
    environment:
      - SPRING_PROFILE=local
      - JVM_MEMORY=-Xmx4g -Xms4g -XX:MetaspaceSize=200m
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 60s
      retries: 15
    links:
      - redis:redis
    depends_on:
      - redis

